### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by randre70** [konsumer/pciinfo#2]
See also #1 

```
    if (error) throw error;
               ^

Error: Command failed: c:\tests\node_modules\pciinfo\bin\win32\lspci.exe -vv -mm -nn -i 'c:\tests\node_modules\pciinfo\bin\pci.ids.gz'
pcilib: i386-io-windows: IO library initialization failed. Try running from an elevated command prompt.

lspci: Cannot find any working access method.

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
````

**Comment by konsumer** [comment]
can you try with admin permissions? Windows used to allow this in non-admin CMD, but it looks like it doesn't anymore.

**Comment by konsumer** [comment]
We might be able to do something like [this](https://docs.microsoft.com/en-us/previous-versions//bb231618(v=vs.85)), in C++, but I am thinking these no-longer-working higher-level methods for win/mac (see #1) probly need some love.  If `lspci` worked outside of linux, or there were working alternatives around (as there were when I made this lib) then it should be fairly easy to port it to the new way to get a list of pci device-ids (then looked up using [lspci's database](http://pciids.sourceforge.net/).) Since I don't use this library for anything, and haven't in like 3 years, I don't really have too much time to investigate the issue, but I will happily accept PRs.
